services:
  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: dev
    container_name: symfony-php-dev
    volumes:
      - ./symfony:/var/www/html:cached
      - ./.env:/var/www/html/.env:ro
      - symfony_var:/var/www/html/var
    environment:
      APP_ENV: dev
      MAILER_DSN: smtp://mailcatcher:1025
    depends_on:
      - db
      - mailcatcher
    networks:
      - symfony-starter

  nginx:
    image: nginx:1.27-alpine
    container_name: symfony-nginx-dev
    volumes:
      - ./symfony:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - symfony-starter

  db:
    image: postgres:17.8
    container_name: symfony-postgres-dev
    environment:
      POSTGRES_USER: symfony-starter
      POSTGRES_PASSWORD: symfony-starter
      POSTGRES_DB: symfony-starter
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - symfony-starter

  mailcatcher:
    image: sj26/mailcatcher
    container_name: symfony-mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - symfony-starter

volumes:
  postgres_data:
  symfony_var:

networks:
  symfony-starter: